"""remove user_transactions table becauses of wrong relationship

Revision ID: 245389338101
Revises: d9bc9b58728d
Create Date: 2023-08-12 18:21:03.727235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245389338101'
down_revision: Union[str, None] = 'd9bc9b58728d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_transactions',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'transaction_id')
    )
    # ### end Alembic commands ###
